;/*FB_PKG_DELIM*/

__d("BaseTypeaheadBaseStaticDataSource",["BaseTypeaheadDataCacheProvider","BaseTypeaheadInMemoryMapDataCache","baseTypeaheadStartsWithMatchBuilder"],(function(a,b,c,d,e,f,g){"use strict";a=function(){function a(a){var b=a.entries,d=a.keyBuilder;a=a.matchBuilder;a=a===void 0?c("baseTypeaheadStartsWithMatchBuilder"):a;this.$1=new(c("BaseTypeaheadDataCacheProvider"))({cache:new(c("BaseTypeaheadInMemoryMapDataCache"))(),keyBuilder:d,matchBuilder:a});this.$1.add(b)}var b=a.prototype;b.fetchCache=function(a){var b=a.query;return{entries:this.$1.match(b),params:a}};return a}();g["default"]=a}),98);
__d("CometComposerValidationErrorsContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext({});g["default"]=b}),98);
__d("CometOnBeforeUnload.react",["useOnBeforeUnload"],(function(a,b,c,d,e,f,g){"use strict";function a(a){a=a.onBeforeUnload;c("useOnBeforeUnload")(a);return null}g["default"]=a}),98);
__d("CometTypeaheadViewList.react",["CometCompositeStructureContext","getItemRoleFromCompositeRole","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));h.useMemo;function a(a){var b=d("react-compiler-runtime").c(16),e,f,g,h,j;b[0]!==a?(e=a.ariaProps,f=a.children,g=a.entries,h=a.highlightedEntry,j=babelHelpers.objectWithoutPropertiesLoose(a,["ariaProps","children","entries","highlightedEntry"]),b[0]=a,b[1]=e,b[2]=f,b[3]=g,b[4]=h,b[5]=j):(e=b[1],f=b[2],g=b[3],h=b[4],j=b[5]);var k=h!=null?h.key:null;a=e.role;b[6]!==a?(h=babelHelpers["extends"]({},a!=null?{role:a}:{}),b[6]=a,b[7]=h):h=b[7];h=h;h=h;var l;if(b[8]!==k||b[9]!==e||b[10]!==f||b[11]!==h||b[12]!==g||b[13]!==j||b[14]!==a){var m=c("getItemRoleFromCompositeRole")(a);l=g!=null&&g.length>0?i.jsx("ul",babelHelpers["extends"]({},e,{className:"x78zum5 xdt5ytf x1iyjqo2","data-testid":void 0,children:i.jsx(c("CometCompositeStructureContext").Provider,{value:h,children:g.map(function(a,b){var c=k===a.key;return f({entry:a,index:b,isActive:c,itemRole:m})})})})):null;b[8]=k;b[9]=e;b[10]=f;b[11]=h;b[12]=g;b[13]=j;b[14]=a;b[15]=l}else l=b[15];return l}g["default"]=a}),98);
__d("CometTypeaheadViewListStrategy.react",["CometTypeaheadViewList.react","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){var b=d("react-compiler-runtime").c(14),e,f;if(b[0]!==a){var g=a.ariaProps,h=a.entries;a.extraViewProps;var j=a.highlightedEntry;a.isLoading;a.onAbandonTypeahead_DO_NOT_USE;var k=a.viewItemStrategyRenderer,l=babelHelpers.objectWithoutPropertiesLoose(a,["ariaProps","entries","extraViewProps","highlightedEntry","isLoading","onAbandonTypeahead_DO_NOT_USE","viewItemStrategyRenderer"]);g=g;h=h;j=j;e=k;f=l;b[0]=a;b[1]=e;b[2]=g;b[3]=h;b[4]=j;b[5]=f}else e=b[1],g=b[2],h=b[3],j=b[4],f=b[5];b[6]!==e||b[7]!==f?(k=function(a){var b=a.entry,c=a.isActive;a=a.itemRole;return i.createElement(e,babelHelpers["extends"]({},f,{entry:b,isActive:c,key:b.key,role:a}))},b[6]=e,b[7]=f,b[8]=k):k=b[8];b[9]!==g||b[10]!==h||b[11]!==j||b[12]!==k?(l=i.jsx(c("CometTypeaheadViewList.react"),{ariaProps:g,entries:h,highlightedEntry:j,testid:void 0,children:k}),b[9]=g,b[10]=h,b[11]=j,b[12]=k,b[13]=l):l=b[13];return l}g["default"]=a}),98);
__d("GroupCometComposerCreateDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8122278791206178"}),null);
__d("TCometComposerTarget",["$InternalEnum"],(function(a,b,c,d,e,f){"use strict";var g=b("$InternalEnum")({Event:"event",Feed:"feed",Group:"group",Page:"page",Profile:"profile",Unknown:"unknown"});function a(a){switch(a){case"event":return g.Event;case"feed":return g.Feed;case"group":return g.Group;case"page":return g.Page;case"profile":return g.Profile}return g.Unknown}f.ComposerTargetType=g;f.getComposerTargetType=a}),66);
__d("createComposerDeferredPlugin",["react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;var j=b.useEffect,k=b.useRef,l=b.useState;function a(a){function b(b){var c=k(a.getModuleIfRequireable()),d=l(c.current!=null);d[0];var e=d[1];j(function(){var b=a.onReady(function(a){c.current=a,e(!0)});b=b.remove;return b},[]);if(c.current!=null){d=c.current;return i.jsx(d,babelHelpers["extends"]({},b))}return null}return i.memo(b)}g["default"]=a}),98);
__d("getComposerUnsavedChangesAlert",["fbt","CometComposerDirtyTracker"],(function(a,b,c,d,e,f,g,h){"use strict";function a(a){return{primaryAction:function(b,c){d("CometComposerDirtyTracker").setIsComposerDirty(a.creationSessionID,!1),c()},primaryButtonLabel:h._("__JHASH__96Xlg9BXGtR__JHASH__"),secondaryButtonLabel:h._("__JHASH__cME-sHhRrLb__JHASH__"),title:h._("__JHASH__O8euS0saaX0__JHASH__"),warnMessage:h._("__JHASH__uuJRtZ_dgpl__JHASH__")}}g["default"]=a}),226);
__d("getPlainTextFromDeferredDraftEditorState_DEPRECATED_DO_NOT_USE",[],(function(a,b,c,d,e,f){"use strict";function a(a){switch(a.__type){case"plain-text":return a.text;case"editor-state-based":return a.draftEditorState.getCurrentContent().getPlainText();default:return a}}f["default"]=a}),66);
__d("useCometTypeaheadViewListStrategy",["CometTypeaheadProgressGlimmer.react","CometTypeaheadViewListStrategy.react","react","react-compiler-runtime","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||(i=d("react"));i.useCallback;function a(a){var b=d("react-compiler-runtime").c(8),e=a.emptyStateContent,f=a.extraViewProps,g=a.loadingState,i=a.nullstateContent,k=a.viewItemStrategyRenderer,l=a.viewListStrategyRenderer,m=a.viewXStyle,n=l===void 0?c("CometTypeaheadViewListStrategy.react"):l;b[0]!==n||b[1]!==e||b[2]!==f||b[3]!==g||b[4]!==i||b[5]!==k||b[6]!==m?(a=function(a){var b=a.entries,d=a.isLoading,l=a.queryString;a=babelHelpers.objectWithoutPropertiesLoose(a,["entries","isLoading","queryString"]);if(l.length===0&&i!=null)return i;return!d&&b.length===0&&e!=null?e:j.jsxs("div",babelHelpers["extends"]({},(h||(h=c("stylex"))).props([m]),{children:[j.jsx(n,babelHelpers["extends"]({},a,{entries:b,extraViewProps:f,isLoading:!1,queryString:l,viewItemStrategyRenderer:k})),d&&((a=g)!=null?a:j.jsx(c("CometTypeaheadProgressGlimmer.react"),{}))]}))},b[0]=n,b[1]=e,b[2]=f,b[3]=g,b[4]=i,b[5]=k,b[6]=m,b[7]=a):a=b[7];return a}g["default"]=a}),98);
__d("useComposerTerminalEventLog",["RunComet","cometComposerLogger","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");b.useCallback;var i=b.useEffect;function a(a,b){var e=d("react-compiler-runtime").c(6),f;e[0]!==b||e[1]!==a?(f=function(){if(a()){var d=b();d!=null&&c("cometComposerLogger")({fields:{terminalReason:"shutdown"},type:"COMPOSER_POST_TERMINAL"},d)}},e[0]=b,e[1]=a,e[2]=f):f=e[2];var g=f,h;e[3]!==g?(f=function(){var a=d("RunComet").onUnload(g);return function(){a&&a.remove()}},h=[g],e[3]=g,e[4]=f,e[5]=h):(f=e[4],h=e[5]);i(f,h)}g["default"]=a}),98);